apiVersion: v1
kind: Pod
metadata:
  name: writer1
  labels:
    app: writer
spec:
  containers:
    - name: writer
      image: vmerv/storage:fat-writer
      imagePullPolicy: Always
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: db-password
      ports:
        - name: main
          containerPort: 8080
    - name: db
      image: vmerv/storage:metadatadb-v1.0
      ports:
        - name: main
          containerPort: 5432
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
spec:
  containers:
    - name: main
      image: curlimages/curl
      command: [ "sleep", "600" ]

