apiVersion: v1
kind: Pod
metadata:
  name: writer1
  labels:
    app: writer
spec:
  containers:
    - name: writer
      image: vmerv/storage:writer-v1.0
      ports:
        - name: main
          containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
spec:
  containers:
    - name: main
      image: curlimages/curl
      command: [ "sleep", "600" ]

